name: github-tools

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # At 00:00 on Sunday.
    # https://crontab.guru/#0_0_*_*_7
    - cron:  '30 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.15'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_ANDROMEDARABBIT }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_ANDROMEDARABBIT }}
